# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

# On Towaki's machine with a RTX8000 on the V8, this code takes:
# 3:41 script runtime as reported on tensorboard
# 23.54 PSNR at the final validation

global:
    exp_name: 'toon-nerf-reg'

optimizer:
    # optimizer_type: 'rmsprop'
    # lr: 0.001
    optimizer_type: 'adam'
    lr: 0.001
    grid_lr_weight: 100.0

dataset:
    dataset_type: 'multiview'
    # num_rays_sampled_per_img: 4096
    num_rays_sampled_per_img: 8192
    multiview_dataset_format: 'standard'
    mip: 1
    bg_color: 'white'

renderer:
    tracer_type: 'PackedRFTracer'
    num_steps: 512
    # num_steps: 256
    raymarch_type: 'ray'
    render_batch: 8192
    camera_origin:
        - 0.0
        - -4.0
        - 0.0
    camera_lookat:
        - 0.0
        - 0.0
        - 0.0
    shading_mode: 'rb'
    render_res:
        - 1000
        - 1000
    # tracer_type: 'PackedSDFTracer'
    # num_steps: 128
    # render_batch: 0
    # step_size: 0.8
    # camera_origin:
    #     - -2.8
    #     - 2.3
    #     - -2.8
    # shading_mode: 'matcap'
    # render_res:
    #     - 1024
    #     - 1024
    # shadow: False

trainer:
    trainer_type: 'ToonTrainer'
    batch_size: 2
    model_format: 'full'
    only_last: 'True'
    epochs: 2000
    valid_every: 2000
    save_every: 2000
    render_every: 2000
    # epochs: 1000
    # valid_every: 1000
    # save_every: 1000
    # render_every: 1000
    # epochs: 200
    # valid_every: 200
    # save_every: 200
    # render_every: 200
    # epochs: 50
    # valid_every: 50
    # save_every: 50
    # render_every: 50
    # epochs: 8
    # valid_every: 8
    # save_every: 8
    # render_every: 8
    # epochs: 1
    # valid_every: 1
    # save_every: 1
    # render_every: 1

grid:
    # grid_type: 'OctreeGrid'
    # interpolation_type: 'linear'
    # multiscale_type: 'sum'
    # feature_dim: 16
    # feature_std: 0.01
    # base_lod: 8
    # num_lods: 1
    grid_type: 'TriplanarGrid'
    interpolation_type: 'linear'
    multiscale_type: 'sum'
    feature_dim: 32
    feature_std: 0.01
    base_lod: 8
    num_lods: 1
    # grid_type: 'HashGrid'
    # interpolation_type: 'linear'
    # multiscale_type: 'cat'
    # feature_dim: 16
    # feature_std: 0.01
    # num_lods: 16
    # tree_type: 'geometric'
    # max_grid_res: 2048
    # codebook_bitwidth: 19

net:
    nef_type: 'ToonNeuralField'
    hidden_dim: 256
    num_layers: 2
    out_dim: 4

embedder:
    embedder_type: 'positional'
